version: '3'

services:
  frontend:
    container_name: frontend-app-example
    restart: always
    build: ./frontend-app
    environment:
      - WORKDIR=/app/user-selected-directory
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  backend:
    container_name: backend-app-example
    restart: always
    build: ./backend-app
    environment:
      - WORKDIR=/app/user-selected-directory
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodatabase
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data.json:/data/data.json:ro
    
